# Generated by Django 3.2.25 on 2024-12-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userapplication',
            table='UserApplication',
        ),
    ]
