# Generated by Django 3.2.25 on 2024-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('FINISH', '已完成'), ('UNFINISH', '未完成')], max_length=20, null=True),
        ),
    ]
