# Generated by Django 3.2.25 on 2024-12-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userapplication_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='name',
        ),
        migrations.AddField(
            model_name='userapplication',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.member'),
        ),
    ]
