# Generated by Django 3.2.25 on 2024-12-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_maintainrecord_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintainrecord',
            old_name='time',
            new_name='createdTime',
        ),
        migrations.AddField(
            model_name='maintainrecord',
            name='finishTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('In', '库中'), ('BORROWING', '租赁中'), ('IN_MAINTENANCE', '维护中'), ('DAMAGE', '损坏'), ('THROWN', '已报废')], max_length=20),
        ),
    ]
