# Generated by Django 3.2.25 on 2024-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20241205_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
