# Generated by Django 3.2.25 on 2024-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userapplication_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='message',
            field=models.CharField(max_length=300, null=True, verbose_name='物资信息'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='usage',
            field=models.CharField(max_length=300, null=True, verbose_name='物资用途'),
        ),
    ]
