# Generated by Django 3.2.25 on 2024-12-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20241205_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_records', to='web.member'),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('PURCHASE_REQUEST', '物资采购申请'), ('DISPOSAL', '物资报废'), ('MAINTENANCE', '物资维修'), ('TRANSFER', '物资转移')], max_length=30),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='reply',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('WAITING', '待确认'), ('REFUSE', '拒绝'), ('APPROVAL', '同意')], max_length=30),
        ),
    ]
