# Generated by Django 3.2.25 on 2024-12-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_approvalrecord_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('PURCHASE_REQUEST', '物资采购申请'), ('DISPOSAL', '物资报废申请'), ('MAINTENANCE', '物资维修申请')], max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PROCURING', '采购中'), ('PROCURED', '已采购')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
