# Generated by Django 3.2.25 on 2024-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20241208_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='threshold',
            field=models.IntegerField(null=True),
        ),
    ]
