# Generated by Django 3.2.25 on 2024-12-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_purchaseorder_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.member'),
        ),
    ]
