# Generated by Django 3.2.25 on 2024-12-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_purchaseorder_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='location',
        ),
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
    ]
