# Generated by Django 3.2.25 on 2024-12-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20241208_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
    ]
