# Generated by Django 3.2.25 on 2024-12-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseReturn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('LEASING', '租赁中'), ('RETURNED', '已归还'), ('LOST', '已丢失'), ('OVERDUE', '已逾期')], max_length=20)),
                ('leaseTime', models.DateTimeField(auto_now_add=True)),
                ('returnTime', models.DateTimeField(null=True)),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.material')),
                ('userApplyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userapplication')),
            ],
            options={
                'db_table': 'LeaseReturn',
            },
        ),
    ]
